beyond-sw-camp/be08-fin-HQ-Heroes

- Frontend/src/layout/AppTopbar.vue
프로젝트 이름 수정
<br>
close #3 
<br>
> [desing/#3] 프로젝트 이름 수정

- k8s/frontend/frontend-deploy.yaml
- k8s/frontend/frontend-service.yaml
- k8s/ingress/ingress-omos.yaml
- k8s/mariadb/mariadb-config.yaml
- k8s/mariadb/mariadb-deployment.yaml
- k8s/mariadb/mariadb-pv.yaml
- k8s/mariadb/mariadb-pvc.yaml
- k8s/mariadb/mariadb-secret.yaml
- k8s/mariadb/mariadb-service.yaml
- k8s/role/jenkins-role-binding.yaml
- k8s/service/auth-deploy.yaml
- k8s/service/auth-hpa.yaml
- k8s/service/auth-service.yaml
- k8s/service/calendar-deploy.yaml
- k8s/service/calendar-hpa.yaml
- k8s/service/calendar-service.yaml
- k8s/service/notice-deploy.yaml
- k8s/service/notice-hpa.yaml
- k8s/service/notice-service.yaml
- k8s/service/notification-deploy.yaml
- k8s/service/notification-hpa.yaml
- k8s/service/notification-service.yaml
- k8s/service/student-deploy.yaml
- k8s/service/student-hpa.yaml
- k8s/service/student-service.yaml
kubernetes 파일 세팅
<br>
close #5 
<br>
> [setting/#5] kubernetes 파일 세팅

- .vscode/launch.json
- Frontend/src/layout/AppMenu.vue
- Frontend/src/layout/AppSidebar.vue
- Frontend/src/layout/AttendanceBox.vue
사이드바 메뉴 수정
<br>
close #7 
<br>
> [design/#7] 인사시스템 사이드바 메뉴 수정

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/layout/AppMenu.vue
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/main.js
- Frontend/src/router/index.js
- Frontend/src/views/pages/feedback/FeedBack.vue
- Frontend/src/views/pages/feedback/FeedBackResult.vue
다면 평가 페이지 구현
평가 상세 dialog
평가 결과 페이지
<br>
close #13 
<br>
> [design/#13] 평가 결과 페이지, 다면 평가 페이지 구현

- Frontend/src/router/index.js
> [design/#21] router.js HQattendance 경로 수정

- Frontend/src/views/pages/salary/SalaryDetails.vue
- Frontend/src/views/pages/salary/SalarySummary.vue
- Frontend/src/views/pages/salary/salary-statement.vue
<br>
급여 페이지 퍼블리싱
close #29 
<br>
> [design/#29] 급여 페이지 퍼블리싱

- Frontend/src/router/index.js
- Frontend/src/views/pages/HQattendance/attendanceStatus/leave-status.vue
- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
> [design/#31] 휴가 페이지 수정

- Frontend/src/router/index.js
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
> [design/#33] 자격증 관리 페이지

- Frontend/src/views/pages/salary/SalarySummary.vue
- Frontend/src/views/pages/salary/salary-statement.vue
<br>
급여 페이지 수정
close #35 
<br>
> [design/#35] 급여 페이지 수정

- Frontend/src/router/index.js
> [design/#39] 관리자 기능 라우터 작성

- Frontend/src/router/index.js
- Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
- Frontend/src/views/pages/admin/SendNotificationPage.vue
> [design/#41] 관리자 알림 발송 페이지 수정

- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [design/#43] 관리자 교육 페이지 추가

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
> [design/#47] 관리자 자격증 페이지 추가

- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
> [design/#49] 휴가 페이지 수정

- Frontend/src/views/pages/main/MainPage.vue
> [design/#51] 메인 페이지 알림부분 메세지로 수정

- Frontend/src/views/pages/main/MainPage.vue
> [design/#53] 출퇴근 시간, 휴가 일수, 급여 카드 수정

- Frontend/index.html
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/router/index.js
- Frontend/src/views/pages/profile/ProfilePage.vue
> [design/#55] add profile

- Frontend/src/views/pages/salary/SalaryDetails.vue
- Frontend/src/views/pages/salary/SalarySummary.vue
- Frontend/src/views/pages/salary/salary-statement.vue
<br>
급여 페이지 수정
close #57 
<br>
> [design/#57] 급여 페이지 수정

- Frontend/src/router/index.js
- Frontend/src/views/pages/retire/retirement-funds.vue
<br>
퇴직금 조회 페이지 퍼블리싱
close #59 
<br>
> [design/#59] 퇴직금 조회 페이지 퍼블리싱

- Frontend/src/views/pages/profile/ProfilePage.vue
> [design /#61] profile final

- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
- Frontend/src/views/pages/feedback/FeedBackPage.vue
- Frontend/src/views/pages/feedback/FeedBackResultPage.vue
사원 수정 페이지
회원 수정 다이어로그 초안
<br>
close #63 
<br>
> [design/#63] 사원 정보 수정 페이지, 사이드 바 아이콘 추가

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 페이지 퍼블리싱
close #64 
<br>
> [design/#64] : 공지사항 페이지 퍼블리싱

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [design/#67] 관리자 교육, 자격증 페이지 정렬 적용

- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
> [design /#71] employeeList 칭찬기능 삭제 및 상태 추가

- Backend/Heroes/src/main/java/com/hq/heroes/feedback/controller/FeedbackController.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/dto/FeedbackDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/repository/FeedbackReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackService.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
평가, 메시지(공지, 알림) 초기 구현
<br>
close #77 
<br>
> [feat/#77] 평가, 메시지(공지, 알림) 초기 구현

- Backend/Heroes/src/main/java/com/hq/heroes/feedback/controller/FeedbackController.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/dto/FeedbackDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/repository/FeedbackReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackService.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
> develop to main

- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/SendNotificationPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
> [design#80] button color change

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/JobRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/PositionRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
> [feat#82] employee 초기 셋팅

- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [design/#86] 교육 신청, 교육 이력 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendacneRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
> [feat/#90] attendance 초기 세팅 및 자료형 변경

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
> [feat/#92] education 초기 세팅

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/enums/Status.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomOAuth2UserService.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomUserDetailsService.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/resources/application.yml
사원 테이블 정의, 사원 고유 ID 생성 기능 구현
<br>
close #94 
<br>
> [feat/#94] 사원 테이블 정의, 사원 고유 ID 생성 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
> [feat/#96] entity 매핑설정

- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
> [feat/#98] education entity 생성

- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/enums/FeedbackStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/NotificationStatus.java
feedback, notice, notification entity setting
<br>
close #100 
<br>
> [feat/#100] feedback, notice, notification entity setting

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
> [feat/#101] attendance 엔티티 및 enum 추가

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
> [feat#103] entity 매핑 수정

- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/course.java
> [feat/#106] education & course 엔티티 추가 및 매핑 수정

- Frontend/src/views/pages/salary/salary-statement.vue
> [design/#108] salaryPage 디자인

- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
- Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/enums/Status.java
- Frontend/src/views/pages/salary/salary-statement.vue
<br>
엔티티 생성 및 자료형 수정
close #110 
<br>
> [feat/#110] 엔티티 생성 및 자료형 수정

- Backend/Heroes/.gitignore
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/resources/application.yml
entity 부동 소수점 버그 해결
<br>
close #112 
<br>
> [fix/#112] entity 부동 소수점 버그 해결

- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/enums/NoticeCategory.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/main/service/noticeService.js
메인 공지사항 조회
<br>
close #114 
<br>
> [feat/#114] 공지사항 RestAPI 구현 및 적

- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/enums/NoticeCategory.java
- Frontend/src/views/pages/admin/service/adminNoticeService.js
- Frontend/src/views/pages/main/MainPage.vue
공지사항 카테고리 한글로 수정
<br>
close #
<br>
> [design#121] 메인 공지사항 카테고리 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/DepartmentDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/TeamDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
> [feat/#117] employee list 백엔드 개발

- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 페이지 디자인 수정
close #119 
<br>
> [design/#119] 공지사항 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/DepartmentDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
> [refactor/#121] employeeList 부서 및 팀 기반 검색 기능 리팩토링

- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 페이지 수정
close #123 
<br>
> [design/#123] 공지사항 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendacneRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
> [Feat/#127] 월 근태 현황 조회 기능

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
> [feat/#129] vacation 기본 코드

- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 페이지 수정
close #131 
<br>
> [design/#131] 공지사항 페이지 수정

- Backend/.idea/Backend.iml
- Backend/.idea/misc.xml
- Backend/.idea/modules.xml
- Backend/.idea/vcs.xml
- Backend/.idea/workspace.xml
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/service/adminNoticeService.js
> [feat/#134] 공지사항 백엔드 API 통신 구현 및 필터링

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
> [Feat/design/#136] 교육 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
> [feat/#138] 휴가 신청, 휴가 조회 기능 추가

- Frontend/package-lock.json
- Frontend/src/views/pages/education/education-management/EducationApply.vue
> [design/#140] education apply design update

- Frontend/src/views/pages/profile/ProfilePage.vue
> [design/#142] profile 파일 업로드시 미리보기 기능 추가

- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
> [design/#144] employee 모달 창 디자인 수정 및 오타 수정

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationTemplate.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/controller/FeedbackController.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/dto/FeedbackDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/enums/FeedbackStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/repository/FeedbackReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackService.java
- Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackServiceImpl.java
feedback -> evaluation로 이름 수정 및 엔티티 수정
<br>
close #150 
<br>
> [refactor#150] feedback -> evaluation로 이름 수정 및 엔티티 수정

- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
<br>
admin Employee Info Update
close #154 
<br>
> [design/#154] admin Employee Info Update

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
> [design/#156] 교육 및 자격증 수정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
> [design/#158] notice list sort 및 admin employee 상세 정보 input readonly 제거

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
> [design/#160] 휴가 신청 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
평가 기준 및 평가 기록 조회, 등록, 수정, 삭제 기능 추가
<br>
close #164 
<br>
> [feat#164] 평가 기준 및 평가 기록 조회, 등록, 수정, 삭제 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
회원가입 기능 구현
<br>
close #168 
<br>
> [feat#168] 회원가입 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/CertificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/educationCategory/entity/EducationCategory.java
- Backend/Heroes/src/main/java/com/hq/heroes/educationCurriculum/entity/EducationCurriculum.java
- Backend/Heroes/src/main/java/com/hq/heroes/employeeCertification/entity/EmployeeCertification.java
교육 엔티티 수정 및 추가
<br>
close #172 
<br>
> [feat#172] 교육 엔티티 수정 및 추가

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
<br>
급여 기능 구현 및 PK 이름 수정
close #180 
<br>
> [feat/#180] 급여 기능 구현 및 PK 이름 수정

- Frontend/src/views/pages/admin/NoticeWritePage.vue
> [design/#184] NoticeWritePage 디자인 수정

- Frontend/src/service/NodeService.js
- Frontend/src/views/pages/admin/SendNotificationPage.vue
- Frontend/src/views/pages/auth/service/authService.js
사원 리스트와 알림 작성 템플릿 추가
<br>
close #186 
<br>
> [design#186] 알림 발송 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/JobDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/PositionDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/JobRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/PositionRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/auth/service/authService.js
회원가입 양식 1
회원가입 양식 2
회원가입 성공 확인
DB에서 가입된 사원 확인
<br>
close #188 
<br>
> feat : 회원가입 기능 구체화 및 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/ReissueController.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/main.js
- Frontend/src/stores/authStore.js
- Frontend/src/views/pages/auth/LoginPage.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/auth/service/fetchAuthorizedPage.js
- Frontend/src/views/pages/auth/service/fetchReissue.js
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
로그인이 안되어 있을 때 사원 찾기, 사이드바
로그인 성공
로컬 스토리지에 데이터 저장
access토큰과 refresh토큰 쿠키로 저장
pinia authStore를 통해 상태관리
로그인 후 사이드바에 로그인 된 사용자 정보 표시
사원 찾기 api 호출 성공
<br>
close #192 
<br>
> [feat#192] 로그인 기능 구현 및 후처리

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [design/#194] 교육 및 자격증 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
department_id -> dept_id
<br>
close #198 
<br>
> [refactor#198] department_id -> dept_id

- Frontend/src/router/index.js
> [refactor/#200] 경로 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/profile/ProfilePage.vue
employee feat and refactor
<br>
close #203 
<br>
> [feat#203] employee feat and refactor

- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCategory.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
교육 및 자격증 entity 수정
<br>
close #207 
<br>
> [feat/#207]교육 및 자격증 entity 수정

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
> [feat/#209] attendance 엔티티 수정

- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
<br>
salary Date -> LocalDateTime 변경
close #211 
<br>
> [feat/#211] salary Date -> LocalDateTime 변경

- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/enums/NoticeCategory.java
notice 카테고리 수정
<br>
close #{이슈넘버}
<br>
> [refactor] notice 카테고리 수정

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
> [feat/#216] attendanceServiceImpl 변경

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/UploadProperties.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/resources/application.yml
파일 업로드 기능 구현중
<br>
close #218 
<br>
> [feat#218] 파일 업로드 기능 구현중

- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/NoticeCategory.java
<br>
noticeCategory 오타 수정
close #220 
<br>
> [refactor/#220] noticeCategory column 이름 오타 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
업로드 된 파일 가져오기 구현
<br>
close #222 
<br>
> [feat/#222] 업로드 된 파일 가져오기 구현

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
employeeList 수정
<br>
close #224 
<br>
> [refactor/#224]  employeeList 수정

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationCriteria.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationForm.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationFormRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
평가 양식 엔티티 및 DTO 추가
<br>
close #229 
<br>
> [feat#229] 평가 양식 엔티티 및 DTO 추가

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationFormController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationForm.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationFormService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationFormServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
평가 관련 CRUD 기능 구현
<br>
close #231 
<br>
> [feat#231] 평가 관련 CRUD 기능 구현

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [design/#233] 관리자 교육 및 자격증 수정 그리고 사원 교육 및 자격증 수정

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
> [design/#235] 휴가 신청 페이지 수정

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
> [feat/#237] 휴가 신청 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeCategoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeCategoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryReposiroty.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/service/adminNoticeCategoryService.js
- Frontend/src/views/pages/admin/service/adminNoticeService.js
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/main/MainPage.vue
<br>
notice 기능 구현
close #241 
<br>
> [feat/#241] notice 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
회원가입 쪽 UI 수정
평가 쪽 UI 수정
<br>
close #247 
<br>
> [design#247] 평가 및 회원가입 UI 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
- Frontend/package-lock.json
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/stores/authStore.js
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/auth/service/fetchReissue.js
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
로컬 스토리지에 access JWT토큰을 통해 api요청 구현, 재갱신 구현 중
<br>
close #249 
<br>
> [feat#249] 로컬 스토리지에 access JWT토큰을 통해 api요청 구현, 재갱신 구현 중

- Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/service/adminNoticeService.js
- Frontend/src/views/pages/main/MainPage.vue
<br>
공지사항 삭제, 추가 구현
close #251 
<br>
> [refactor/#251] 공지사항 삭제, 추가 구현

- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/auth/service/fetchReissue.js
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
재 갱신 기능 구현
<br>
close #253 
<br>
> [feat#253] 재 갱신 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationCategoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationCurriculumDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationCategoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationCurriculumRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
> [feat/#255] 교육 코드 수정

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
휴가 승인페이지(사원) 추가
<br>
close #257 
<br>
> [feat/#257] 휴가 승인페이지(사원) 추가

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/NotificationCategory.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
알림 api 구현
<br>
close #261 
<br>
> [feat#261] 알림 api 구현

- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
<br>
profile Update
close #263 
<br>
> [feat/#263] profile Update

- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationCriteriaRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
평가 디테일 화면
<br>
close #265 
<br>
> [design#265] 부서별 평가 기준 화면 구현

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
> [design/#267] 관리자 교육 페이지 수정 & 공지사항 수정 페이지에 카테고리 추가

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
평가 등록 기능 구현
<br>
close #269 
<br>
> [feat#269] 평가 등록 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
> [feat/#271] 자격증 엔티티 수정, 교육 & 자격증 코드 수정

- Frontend/src/views/pages/auth/service/AuthApiService.js
fetchPost 상태코드 수정 200 -> 201 무한 reissue발생 버그 해결
<br>
close #273 
<br>
> [fix#273] fetchPost 상태코드 수정 200 -> 201 무한 reissue발생 버그 해결

- Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/CustomEmployeeDetails.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
jwt filter에서 역할, 사용자 ID 확인 기능 구현
<br>
close #275 
<br>
> [feat#275] jwt filter에서 역할, 사용자 ID 확인 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
휴가 승인(관리자, 팀장) 페이지 추가
<br>
close #277 
<br>
> [feat/#277] 휴가 승인(관리자, 팀장) 페이지 추가

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
axios에서 fetchGet으로 변경
<br>
close #281 
<br>
> [feat/#281] axios에서 fetchGet으로 변경

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/EmployeeCertificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/package-lock.json
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageCertificationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
> [Feat&design/#283] 교육 및 자격증 수정

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
로그인한 팀원의 평가 결과 조회 기능 구현
결과 리스트
상세 보기
<br>
close #285 
<br>
> [feat#285] 로그인한 팀원의 평가 결과 조회 기능 구현

- Frontend/src/layout/AppLayout.vue
- Frontend/src/views/pages/admin/SendNotificationPage.vue
사원 목록 선택 영역
<br>
close #287 
<br>
> [design#287] 알림 발송 사원 목록 트리 부서 > 팀 > 사원순으로 구현 및 프로필 사진 표시

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomLogoutFilter.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/RedisConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Backend/Heroes/src/main/resources/application.yml
refresh 토큰 데이터를 Redis를 사용해서 관리하도록 리팩토링
<br>
close #289 
<br>
> [refactor#289] refresh 토큰 데이터를 Redis를 사용해서 관리하도록 리팩토링

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationCriteria.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
- Frontend/src/layout/AppMenu.vue
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageEvaluationCriteriaPage.vue
평가 기준 관리 기능 구현
<br>
close #291 
<br>
> [feat#291] 평가 기준 관리 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/DeductController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/DeductDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/DeductRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/DeductService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/DeductServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
- Frontend/src/views/pages/salary/deductService.js
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
<br>
급여 내역 조회 기능 구현
close #293 
<br>
> [feat/#293] 급여 내역 조회 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationCategoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationCategoryReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationCategoryResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationCategoryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationCategoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/admin/SendNotificationPage.vue
알림 카테고리 파일 추가 및 알림 발송 기능 구현
<br>
close #295 
<br>
> [feat#295] 알림 카테고리 파일 추가 및 알림 발송 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/main/service/notificationService.js
받은 알림 조회 기능 구현
<br>
close #297 
<br>
> [feat#297] 받은 알림 조회 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/layout/AttendanceBox.vue
출퇴근 버튼 사용하여서 근태 관리
<br>
close #299 
<br>
> [feat/#299] : 출퇴근 버튼 사용하여서 근태 관리

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
월 근태 현황 기능 추가
<br>
close #303 
<br>
> [feat/#303] 월 근태 현황 기능 추가

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTUtil.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Backend/Heroes/src/main/resources/application.yml
System.out -> log.debug로 리팩토링, 필요없는 주석 삭제
<br>
close #305 
<br>
> [refactor#305] System.out -> log.debug로 리팩토링, 필요없는 주석 삭제

- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
휴가 승인 거절 추가
<br>
close #307 
<br>
> [design/#307] 휴가 승인 거절 추가

- Frontend/src/views/pages/admin/SendNotificationPage.vue
알림 작성 페이지 디자인 수정
<br>
close #311 
<br>
> [design#311] 알림 작성 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
캘린더에 내 일정 추가 기능
<br>
close #313 
<br>
> [feat/#313] 캘린더에 내 일정 추가 기능

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/entity/Event.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/repository/EventRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
캘린더에서 생성하는 이벤트를 저장하기 위한 엔티티
<br>
close #315 
<br>
> [feat/#315] 캘린더에서 생성하는 이벤트를 저장하기 위한 엔티티

- Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
안쓰는 Import 제거
<br>
close #319 
<br>
> [refactor/#319] 안쓰는 Import 제거

- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/DeductController.java
<br>
안쓰는 import 제거
close #321 
<br>
> [refactor/#321] 안쓰는 import 제거

- Frontend/src/views/pages/salary/salary-statement.vue
<br>
salary 지급 상태 오류 수정
close #325 
<br>
> [fix/#325] salary 지급 상태 오류 수정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/AdminEmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/PositionRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/auth/service/authService.js
employeeRefactor
<br>
close #327 
<br>
> [refactor/#327] employeeRefactor

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
> [refator/#329] import문 수정

- Frontend/src/views/pages/profile/ProfilePage.vue
profile readonly 속성 디자인
<br>
close #331 
<br>
> [design/#331] profile readonly 속성 디자인

- Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/RedisConfig.java
- Frontend/src/views/pages/auth/service/authService.js
설명 주석 추가
<br>
close #333 
<br>
> [refactor#333] 설명 주석 추가

- Frontend/src/views/pages/auth/SignUpPage.vue
회원가입 유효성 검사 추가
<br>
close #337 
<br>
> [feat#337] 회원가입 유효성 검사 추가

- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
<br>
월 근태, 휴가 승인 DataTable 수정
close #339 
<br>
> [design/#339] 월 근태, 휴가 승인 DataTable 수정

- Frontend/src/layout/AttendanceBox.vue
AttendanceBox에 프로필 이미지 추가, 퇴근 색상 변경 
<br>
close #343 
<br>
> [design/#343] AttendanceBox에 프로필 이미지 추가, 퇴근 색상 변경 

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/enums/CourseStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [Feat&design/#345] 교육 수정

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
> [Feat&design/#347] 자격증 수정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/DeductDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryHistoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/SalaryHistory.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/DeductRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
<br>
salary 엔터티 생성 및 조회 기능 구현
close #349 
<br>
> [feat/#349] salary 엔터티 생성 및 조회 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationCategoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationCategoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeCategoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
- Frontend/src/views/pages/admin/service/adminNoticeCategoryService.js
공지사항, 교육 카테고리 통합 및 글쓰기 이동
<br>
close #351 
<br>
> [refactor/#351] 공지사항, 교육 카테고리 통합 및 글쓰기 이동

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
fetchPost 수정 및 출퇴근 기능 추가
<br>
close #355 
<br>
> [feat/#355] fetchPost 수정 및 출퇴근 기능 추가

- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/main/MainPage.vue
총 근무시간 시간, 분, 초 단위로 변경
<br>
close #357 
<br>
> [design/#357] 총 근무시간 시간, 분, 초 단위로 변경

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
- Frontend/src/views/pages/salary/deductService.js
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
<br>
공제액 조회 구현
close #359 
<br>
> [feat/#359] 공제액 조회 구현

- Backend/Heroes/src/main/java/com/hq/heroes/common/controller/ImageUploadController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/EducationWritePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
공지사항 작성 기능 구현
<br>
close #361 
<br>
> [feat/#361] create notice

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/RefreshRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/controller/EmailController.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/dto/AuthCodeReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailMessage.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/entity/AuthCode.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailService.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
- Backend/Heroes/src/main/resources/templates/mails/authCode.html
- Backend/Heroes/src/main/resources/templates/mails/changePassword.html
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/auth/AdminLoginPage.vue
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/auth/service/fetchReissue.js
관리자 로그인 시 인증번호 메일로 발송 및 2차 인증 구현
<br>
close #362 
<br>
> [feat#353] 관리자 로그인 시 인증번호 메일로 발송 및 2차 인증 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/layout/AttendanceBox.vue
안읽은 알림개수 AttendanceBox에 표시
<br>
close #367 
<br>
> [feat/#367] 안읽은 알림개수 AttendanceBox에 표시

- Frontend/src/views/pages/salary/salary-statement.vue
<br>
급여 상태(지급, 미지급) 색 변경
close #369 
<br>
> [design/#369] 급여 상태(지급, 미지급) 색 변경

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/CertificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [Feat&design/#371]certification

- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/views/pages/admin/SendNotificationPage.vue
발송자 표시 및 사원 트리 검색 필터 추가
<br>
close #373 
<br>
> [design#373] 발송자 표시 및 사원 트리 검색 필터 추가

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/main/service/attendanceService.js
메인 페이지에 출퇴근 시간 출력
<br>
close #375 
<br>
> [feat/#375] 메인 페이지에 출퇴근 시간 출력

- Frontend/src/views/pages/salary/salary-statement.vue
<br>
공제액 계산 함수 생성 및 실지급액 계산
close #377 
<br>
> [feat/#377] 공제액 계산 함수 생성 및 실지급액 계산

- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
Appmenu, 공지사항 페이지 디자인 수정
close #379 
<br>
> [design/#379] Appmenu, 공지사항 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/entity/Event.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
캘린더 이벤트 추가 기능
<br>
close #381 
<br>
> [feat/#381] 캘린더 이벤트 추가 기능

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/main/MainPage.vue
알림 열람 상태 변경 기능 추가
<br>
close #383 
<br>
> [feat#383] 알림 열람 상태 변경 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
자신의 휴가 내역만 보이도록 설정
<br>
close #385 
<br>
> [feat/#385] 자신의 휴가 내역만 보이도록 설정

- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Frontend/package-lock.json
- Frontend/src/main.js
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
<br>
공지사항 조회, 삭제 기능
close #387 
<br>
> [feat/#387] 공지사항 조회, 삭제 기능

- Frontend/src/layout/AppMenu.vue
- Frontend/src/router/index.js
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
> [design/#390] 휴가 승인 페이지와 휴가 상태 확인 페이지 분리

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [Feat&design/#393] 교육 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
educationId 타입 long -> Long
<br>
close #397 
<br>
> [refactor/#397] educationId 타입 long -> Long

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/main/MainPage.vue
<br>
공지사항 hover 적용
close #399 
<br>
> [design/#399] 공지사항 hover 적용

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
휴가 승인 페이지 자신에게 온 신청만 보이게 수정
<br>
close #401 
<br>
> [feat/#401] 휴가 승인 페이지 자신에게 온 신청만 보이게 수정

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/views/pages/admin/EducationWritePage.vue
Education 작성 기능 추가
<br>
close #403 
<br>
> [feat/#403] Write Education

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
- Frontend/src/views/pages/salary/workService.js
<br>
특정 사원의 월별 총 근무 시간 조회
close #405 
<br>
> [feat/#405] 특정 사원의 월별 총 근무 시간 조회

- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [design/#409] 교육 신청하기 및 수강 정원 추가하기

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/main.js
- Frontend/src/views/pages/auth/AdminLoginPage.vue
- Frontend/src/views/pages/auth/LoginPage.vue
로그인 페이지 디자인 수정
<br>
close #411 
<br>
> [design#411] 로그인 페이지 디자인 수정

- Frontend/src/layout/AppTopbar.vue
상단 바에서 알림 Drawer 열기 구현
<br>
close #413 
<br>
> [design#413] 상단 바에서 알림 Drawer 열기 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/main/service/notificationService.js
받은 알림 조회
보낸 알림 조회
알림 리스트 디자인 수정
<br>
close #415 
<br>
> [feat#415] 보낸알림, 받은알림 필터 구현 및 알림 리스트 디자인 수정

- Frontend/src/layout/AttendanceBox.vue
퇴근하기와 동시에 로그아웃 되게 설정
<br>
close #417 
<br>
> [feat/#417] 퇴근하기와 동시에 로그아웃 되게 설정

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/dto/OvertimeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/entity/Overtime.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/entity/enums/OvertimeStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/repository/OvertimeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
- Frontend/src/layout/AppMenu.vue
- Frontend/src/router/index.js
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/overtime/approve-overtime.vue
- Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
연장 근로 관련 기능 추가
<br>
close #419 
<br>
> [feat/#419] 연장 근로 관련 기능 추가

- Frontend/src/layout/AppTopbar.vue
알림 관리 Drawer 디자인 수정
<br>
close #421 
<br>
> [design#421] 알림 관리 Drawer 디자인 수정

- Frontend/package-lock.json
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
공지사항 수정 - 취소 - 수정 시 에디터 내용 보이기 작업중..
<br>
close #{이슈넘버}
<br>
> [refactor/#423] 공지사항 수정 - 취소 - 수정 시 에디터 내용 보이기 작업중..

- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/main/MainPage.vue
알림 관리, 메인 알림 영역 정렬 수정 및 디자인 수정, 삭제 버튼 추가
<br>
close #425 
<br>
> [desgin#425] 알림 관리, 메인 알림 영역 정렬 수정 및 디자인 수정, 삭제 버튼 추가

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/notification/SendNotificationPage.vue
알림 삭제 기능 구현
<br>
close #427 
<br>
> [feat#427] 알림 삭제 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
add courseList
<br>
close #429 
<br>
> [feat/#429] add courseList

- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
<br>
신청 기간 없애기
공지사항에서 취소 누르면 수정 누르기 전 단계로 가기
close #431 
<br>
> [design/#431] 관리자 모드에서 교육 및 공지사항 수정

- Frontend/src/views/pages/admin/EducationWritePage.vue
교육 등록 시 이미지 저장로직 추가
<br>
close #433 
<br>
> [feat/#433] 교육 등록 시 이미지 저장로직 추가

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
- Frontend/package.json
- Frontend/src/views/pages/salary/deductService.js
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
<br>
급여 조회 기능 수정 (fetchGet으로 변경)
close #435 
<br>
> [feat/#435] 급여 조회 기능 수정 (fetchGet으로 변경)

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
다른 팀원 휴가 신청 가능
<br>
close #437 
<br>
> [feat/#437] 다른 팀원 휴가 신청 가능

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
> [Feat&design/#439] education

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
휴가 신청자, 결재자, 대리인 구분 구현
<br>
close #441 
<br>
> [feat/#441] 휴가 신청자, 결재자, 대리인 구분 구현

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
신청자, 대리인, 결재자 requestBody에 추가
<br>
close #441 
<br>
> [feat] 신청자, 대리인, 결재자 requestBody에 추가

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/RetireDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Frontend/src/views/pages/retirement/retirement-funds.vue
- Frontend/src/views/pages/retirement/service/retirementService.js
<br>
퇴직금 조회 기능 구현
close #444 
<br>
> [feat/#444] 퇴직금 조회 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Frontend/src/views/pages/admin/EducationWritePage.vue
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
- Frontend/src/views/pages/admin/service/adminNoticeService.js
공지사항 작성 시 이미지 크기 고정 및 페이지 이동
<br>
close #445 
<br>
> [feat/ #445] 공지사항 작성 시 이미지 크기 고정 및 페이지 이동

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
휴가에서 applicant, employee, approver 구분
<br>
close #448 
<br>
> [feat/#448] 휴가에서 applicant, employee, approver 구분

- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/salary/salary-statement.vue
<br>
모달창 클릭 시 블러 처리
close #450 
<br>
> [design/#450] 모달창 클릭 시 블러 처리

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/package-lock.json
- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
<br>
신청한 교육 상세 모달창
교육 취소 시 alert 창 보이도록
이미 신청한 교육이면 alert 창으로 신청한 교육이라고 하고 신청 못하도록
close #452 
<br>
> [Feat&design/#452] education

- Frontend/src/views/pages/admin/NoticeDetailPage.vue
> [feat/#454] 공지사항 취소

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
- Frontend/src/views/pages/main/MainPage.vue
보류중(ON_HOLD) 추가 및 18:10까지 퇴근기록 없다면 보류 상태로 변경하는 코드 추가
<br>
close #456 
<br>
> [feat/#456] 보류중(ON_HOLD) 추가 및 18:10까지 퇴근기록 없다면 보류 상태로 변경하는 코드 추가

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/PasswordUpdateDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
비밀번호 변경 기능 구현
사원 프로파일에서 비밀번호 변경 버튼을 통해 변경 가능
유효성 검사1
유효성 검사2
비밀번호 변경 성공
<br>
close #458 
<br>
> [feat/#458] 비밀번호 변경 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
> [feat/#460] 공지사항 업데이트 진행중..

- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [design/#462] 자격증 및 교육 검색 부분 수정

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/repository/OvertimeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
연장 근로 시간 체크
<br>
close #464 
<br>
> [feat/#464] 연장 근로 시간 체크

- Frontend/src/views/pages/admin/NoticeWritePage.vue
<br>
notice 뒤로가기 router 설정
close #470 
<br>
> [refactor/#470] notice 뒤로가기 router 설정

- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 목록 검색 버튼 위치 변경
close #472 
<br>
> [design/#472] 공지사항 목록 검색 버튼 위치 변경

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
평가 결과 항목
<br>
close #474 
<br>
> [feat#474] 평가 결과 리스트 항목 수정

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
- Frontend/src/layout/AppMenu.vue
- Frontend/src/router/index.js
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
> [Feat&design/#476] 교육 페이지 추가

- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/salaryService.js
<br>
급여 계산 기능 수정(1년마다 매년 5% 증가)
close #478 
<br>
> [feat/#478] 급여 계산 기능 수정(1년마다 매년 5% 증가)

- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
> [refactor/#480] fetch import 추가

- Backend/Heroes/src/test/java/com/hq/heroes/employee/service/EmployeeServiceImplTest.java
employee 테스트 코드 초기 셋팅
<br>
close #482 
<br>
> [test/#482] employee 테스트 코드 초기 셋팅

- Backend/Heroes/src/test/java/com/hq/heroes/employee/service/EmployeeServiceTest.java
employee Test
<br>
close #484 
<br>
> [test/#484] employee Test

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
<br>
평가 점수에 따른 성과급 생성
close #488 
<br>
> [feat/#488] 평가 점수에 따른 성과급 생성

- Backend/Heroes/src/test/java/com/hq/heroes/notification/service/NotificationServiceTest.java
알림 서비스 테스트 코드 작성
<br>
close #490 
<br>
> [test#490] 알림 서비스 테스트 코드 작성

- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/PasswordUpdateDTO.java
- Backend/Heroes/src/test/java/com/hq/heroes/employee/controller/EmployeeControllerTest.java
EmployeeController Test
<br>
close #492 
<br>
> [test/#492] EmployeeController Test

- Backend/Heroes/src/test/java/com/hq/heroes/employee/controller/EmployeeControllerTest.java
EmployeeControllerTest 비밀번호 변경 실패 테스트
<br>
close #494 
<br>
> [test/#494] EmployeeControllerTest 비밀번호 변경 실패 테스트

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
> [Feat&design/#498] course

- Backend/Heroes/src/test/java/com/hq/heroes/auth/controller/ReissueControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/controller/SignControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/CustomUserDetailsServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/JoinServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/RefreshTokenServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/ReissueServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/common/service/EmailServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/controller/EvaluationControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/service/EvaluationServiceTest.java
auth, common, evaluation test setting
<br>
close #500 
<br>
> [test#500] auth, common, evaluation test setting

- Backend/Heroes/src/test/java/com/hq/heroes/education/service/EducationServiceTest.java
> [test/#502] educationtest 구현

- Backend/Heroes/src/test/java/com/hq/heroes/vacation/service/VacationServiceTest.java
vacationServiceTest 추가
<br>
close #504 
<br>
> [test/#504] vacationServiceTest 추가

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Backend/Heroes/src/test/java/com/hq/heroes/employee/controller/AdminEmployeeControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/employee/controller/EmployeeControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/employee/service/EmployeeServiceTest.java
employee, adminEmployee Test Code 작성
<br>
close #506 
<br>
> [test/#506] employee, adminEmployee Test Code 작성

- Backend/Heroes/src/test/java/com/hq/heroes/vacation/service/VacationServiceTest.java
vacationServiceTest 추가
<br>
close #508 
<br>
> [test/#508] vacationServiceTest 추가

- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/CustomUserDetailsServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/JoinServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/RefreshTokenServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/service/ReissueServiceTest.java
auth service test
<br>
close #509 
<br>
> [test#509] auth service test

- Backend/Heroes/src/test/java/com/hq/heroes/common/service/EmailServiceTest.java
EmailService 테스트 코드 구현
<br>
close #514 
<br>
> [test#514] EmailService 테스트 코드 구현

- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceTest.java
EvaluationCriteriaService 테스트 코드 구현
<br>
close #516 
<br>
> [test#516] EvaluationCriteriaService 테스트 코드 구현

- Backend/Heroes/src/test/java/com/hq/heroes/attendance/service/AttendanceServiceTest.java
attendanceServiceTest 추가
<br>
close #518 
<br>
> [test/#518] attendanceServiceTest 추가

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
- Backend/Heroes/src/test/java/com/hq/heroes/overtime/service/OvertimeServiceTest.java
overtimeServiceTest 추가
<br>
close #520 
<br>
> [test/#520] overtimeServiceTest 추가

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
<br>
평가에 따른 급여 생성 기능 수정
close #522 
<br>
> [feat/#522] 평가에 따른 급여 생성 기능 수정

- Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
- Backend/Heroes/src/test/java/com/hq/heroes/event/service/EventServiceTest.java
eventServiceTest 추가
<br>
close #524 
<br>
> [test/#524] eventServiceTest 추가

- Backend/Heroes/src/test/java/com/hq/heroes/certification/service/CertificationServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/certification/service/EmployeeCertificationServiceTest.java
> [test/#526] certificationTestCode & EmployeeCertificationTestCode 작성

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
<br>
평가 점수에 따른 성과급 생성 기능 수정
close #528 
<br>
> [feat/#528] 평가 점수에 따른 성과급 생성 기능 수정

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
<br>
급여 생성 날짜 수정
close #530 
<br>
> [feat/#530] 급여 생성 날짜 수정

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/controller/ReissueControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/auth/controller/SignControllerTest.java
auth controller test
<br>
close #532 
<br>
> [test#532] auth controller test

- Backend/Heroes/src/test/java/com/hq/heroes/common/config/TestSecurityConfig.java
- Backend/Heroes/src/test/java/com/hq/heroes/common/controller/EmailControllerTest.java
common TestSecurityConfig 작성, EmailControllerTest 테스트 코드 구현
<br>
close #534 
<br>
> [test#534] common TestSecurityConfig 작성, EmailControllerTest 테스트 코드 구현

- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/controller/EvaluationControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/evaluation/service/EvaluationServiceTest.java
evaluation test
<br>
close #538 
<br>
> [test#538] evaluation test

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
- Backend/Heroes/src/test/java/com/hq/heroes/overtime/controller/OvertimeControllerTest.java
overtimeControllerTest 추가
<br>
close #540 
<br>
> [test/#540] overtimeControllerTest 추가

- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
NotificationControllerTest 테스트 코드 구현
<br>
close #542 
<br>
> [test#542] NotificationControllerTest 테스트 코드 구현

- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
<br>
Salary 엔드포인트 변경 및 description 추가
close #546 
<br>
> [refactor/#546] Salary 엔드포인트 변경 및 description 추가

- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
<br>
변수 타입 Double -> double
close #548 
<br>
> [refactor/#548] 변수 타입 Double -> double

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/test/java/com/hq/heroes/event/controller/EventControllerTest.java
eventControllerTest 추가
<br>
close #550 
<br>
> [test/#550] eventControllerTest 추가

- Backend/Heroes/src/test/java/com/hq/heroes/attendance/controller/AttendanceControllerTest.java
AttendanceControllerTest 추가
<br>
close #552 
<br>
> [test/#552] AttendanceControllerTest 추가

- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
<br>
급여 기록이 없을 경우 예외 처리
close #554 
<br>
> [refactor/#554] 급여 기록이 없을 경우 예외 처리

- Backend/Heroes/src/test/java/com/hq/heroes/salary/controller/SalaryControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/salary/controller/SalaryHistoryControllerTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/salary/service/SalaryHistoryServiceTest.java
- Backend/Heroes/src/test/java/com/hq/heroes/salary/service/SalaryServiceTest.java
<br>
급여 관련 테스트 코드 작성
close #556 
<br>
> [test/#556] 급여 관련 테스트 코드 작성

- Frontend/src/views/pages/retirement/service/retirementService.js
- Frontend/src/views/pages/salary/salaryService.js
<br>
엔드포인트 수정
close #558 
<br>
> [refactor/#558] 엔드포인트 수정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/NoticeUpdatePage.vue
notice 수정 페이지 이미지 수정<br>
close #560 
<br>
> [feat/#560] notice 수정 페이지 이미지 수정

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [design/#562] 관리자 교육 & 자격증 dropdown 수정 및 배치 변경

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
팀원 평가 및 평가 결과 확인 기능 구현
팀원 - 평가 결과 리스트 화면
팀원 - 평가 결과 상세 Dialog
팀장 - 팀원 평가 화면
<br>
close #564 
<br>
> [feat#564] 팀원 평가 및 평가 결과 확인 기능 구현

- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/views/pages/admin/ManageNoticePage.vue
<br>
공지사항 목록 최신순 정렬
close #566 
<br>
> [feat/#566] 공지사항 목록 최신순 정렬

- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [design/#568] 관리자 교육 수정 페이지 라우터 수정

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/enums/EmployeeCertificationStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
- Frontend/src/views/pages/admin/EducationUpdatePage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
> [Feat&design/#570] certification

- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/AutoNotificationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationCategoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
> [feat#572] 알림 자동 발송 기능 구현 중

- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
> feat : 휴가 신청, 승인, 반려 알림 발송 구현

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/repository/EventRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
일정 추가 기능
<br>
close #576 
<br>
> [feat/#576] 일정 추가 기능

- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Frontend/src/router/index.js
- Frontend/src/views/pages/admin/EducationUpdatePage.vue
- Frontend/src/views/pages/admin/EducationWritePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [Feat&design/#580] admineducation

- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeUpdatePage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
> [design/#582] 관리자 공지사항 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
> [Feat&design/#584] employee certification

- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
> [design/#586] 교육 승인 페이지 수정 및 localstorage.setItem 제거

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
팀별 휴가 조회
<br>
close #588 
<br>
> [feat/#588] 팀별 휴가 조회

- Frontend/src/views/pages/main/MainPage.vue
<br>
mainPage 공지사항 날짜 수정
close #590 
<br>
> [design/#590] mainPage 공지사항 날짜 수정

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
> refactor : 코드 리팩토링

- Backend/Heroes/build.gradle
- Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/UpdateAnnualLeaveBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/DataDBConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/MetaDBConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/schedule/UpdateAnnualLeaveSchedule.java
- Backend/Heroes/src/main/resources/application.yml
> [feat/#596] employee 입사일 기준 휴가 생성 배치 추가

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Frontend/src/views/pages/salary/salary-statement.vue
- Frontend/src/views/pages/salary/workService.js
<br>
연장 근로 시간 조회
close #600 
<br>
> [feat/#600] 연장 근로 시간 조회

- Frontend/src/views/pages/retirement/retirement-funds.vue
<br>
jobName -> jobRoleName
close #602 
<br>
> [refactor/#602] jobName -> jobRoleName

- Frontend/src/stores/authStore.js
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
- Frontend/src/views/pages/notification/SendNotificationPage.vue
job -> jobRole
<br>
close #604 
<br>
> [refactor#604] job -> jobRole

- Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
- Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
> [refactor/#606] 주석 추가

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
main 페이지 휴가 일수
<br>
close #608 
<br>
> [refactor/#608] main 페이지 휴가 일수

- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SendEvaluationBatch.java
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/notification/SendNotificationPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
main page
<br>
close #610 
<br>
> [refactor/#610] main page

- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/AutoNotificationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
자동 알림 발송 Type 세팅
<br>
close #611 
<br>
> [feat#611] 자동 알림 발송 Type 세팅

- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
내 일정 표시, 카테고리별 필터 생성
<br>
close #621 
<br>
> [feat/#621] 내 일정 표시, 카테고리별 필터 생성

- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
> [design/#623] 교육 상세 페이지 디자인 수정

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
> [design/#627] alert창 및 검색 부분 수정

- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
> [design/#629] alert 창 및 모달창 수정

- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
> [design/#631] alert 창 및 모달창 수정

- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeUpdatePage.vue
공지사항 페이지 필터링 및 정렬
<br>
close #633 
<br>
> [refactor/#633] 공지사항 페이지 필터링 및 정렬

- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
캘린더 필터링 버튼 추가
<br>
close #635 
<br>
> [feat/#635] 캘린더 필터링 버튼 추가

- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
> [design/#637] 전체보기 추가

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
휴가 신청 시 연차 차감 & 연차 없을 시 불가
<br>
close #639 
<br>
> [feat/#639] 휴가 신청 시 연차 차감 & 연차 없을 시 불가

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
엑셀 파일로 내보내기 기능 추가
<br>
close #643 
<br>
> [feat/#643] 엑셀 파일로 내보내기 기능 추가

- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
- Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
연장근로 수정중
<br>
close #645 
<br>
> [feat/#645] 연장근로 수정중

- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
공지사항 페이지 오류 수정 및 sweetalert2 버튼으로 변경
<br>
close #647 
<br>
> [refactor/#647] 공지사항 페이지 오류 수정 및 sweetalert2 버튼으로 변경

- Frontend/src/views/pages/admin/service/adminNoticeService.js
axios 에서 fetchPost,fetchGet, fetchPut, fetchDelete 로 변경
<br>
close #649 
<br>
> [refactor/#649] 공지사항 API 변경

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
> [design/#651] 관리자 자격증 페이지 모달창 안나오는거 해결 및 alert 창 swal로 수정

- Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/AsyncConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationsReqDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/views/pages/auth/service/authService.js
- Frontend/src/views/pages/main/MainPage.vue
자동 알림 발송 비동기 로직 구현
<br>
close #653 
<br>
> [feat#653] 자동 알림 발송 비동기 로직 구현

- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
> [design/#655] education-history 모달창 수정 및 버튼 위치 조정

- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Frontend/src/views/pages/admin/ManageEvaluationCriteriaPage.vue
- Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
- Frontend/src/views/pages/notification/SendNotificationPage.vue
swal로 alert 창 수정 및 알림 수정
<br>
close #657 
<br>
> [design#657] swal로 alert 창 수정 및 알림 수정

- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SendEvaluationBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/UpdateAnnualLeaveBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/DataDBConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/MetaDBConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/schedule/SendEvaluationSchedule.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
send notification batch 적용
<br>
close #659 
<br>
> [feat/#659] send notification batch 적용

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
잔여 연장 근로 시간 조회, 총 연장 근로 시간 조회 분리
<br>
close #661 
<br>
> [feat/#661] 잔여 연장 근로 시간 조회, 총 연장 근로 시간 조회 분리

- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryHistoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Frontend/src/views/pages/salary/salary-statement.vue
모든 급여 관련 데이터 계산 후 DTO 로 반환하도록 변경
<br>
close #663 
<br>
> [refactor/#663] 모든 급여 관련 데이터 계산 후 DTO 로 반환하도록 변경

- Frontend/src/views/pages/main/MainPage.vue
급여일까지 남은 일수 표시
<br>
close #665 
<br>
> [design/#665] 급여일까지 남은 일수 표시

- Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
- Frontend/src/layout/AppMenu.vue
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/router/index.js
- Frontend/src/views/pages/auth/AdminLoginPage.vue
- Frontend/src/views/pages/auth/LoginPage.vue
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
auth 쪽 alert 수정 및 router 수정
<br>
close #667 
<br>
> [design#667] auth 쪽 alert 수정 및 router 수정

- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SendEvaluationBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/schedule/SendEvaluationSchedule.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
dto위치 entity, controller -> service로 이동해서 proxy문제해결
<br>
close #669 
<br>
> [fix/#669] dto위치 entity, controller -> service로 이동해서 proxy문제해결

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
> [refactor/#671] axios에서 fetch로 바꾸기

- Frontend/src/views/pages/admin/EducationUpdatePage.vue
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
> [refactor/#673] 전체적으로 수정

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
휴가 신청 관련 오류 수정
<br>
close #675 
<br>
> [fix/#675] 휴가 신청 관련 오류 수정

- Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryHistoryDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
- Frontend/src/views/pages/salary/salary-statement.vue
급여 데이터 생성하기 위한 로직 추가 및 CSV 파일 내보내기
<br>
close #677 
<br>
> [feat/#677] 급여 데이터 생성하기 위한 로직 추가 및 CSV 파일 내보내기

- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
<br>
자격증 및 사원 자격증 상세 모달창 디자인 변경
close #681 
<br>
> [fix/#681] 자격증 및 사원 자격증 상세 모달창 디자인 변경

- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
시작일보다 종료일이 빠를경우 경고 추가
<br>
close #683 
<br>
> [design/#683] 시작일보다 종료일이 빠를경우 경고 추가

- Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
employee status 추가<br>
close #685 
<br>
> [feat/#685] employee status 추가

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
EmployeeRepository status 필드 누락
<br>
close #687 
<br>
> [fix/#687] EmployeeRepository status 필드 누락

- Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SendEvaluationBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/schedule/SendEvaluationSchedule.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/resources/application.yml
평가 결과 전송 배치 작업 Employee쪽 영속성 문제 해결
<br>
close #689 
<br>
> [fix#689] 평가 결과 전송 배치 작업 Employee쪽 영속성 문제 해결

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/layout/AppTopbar.vue
- Frontend/src/layout/AttendanceBox.vue
- Frontend/src/stores/notificationStore.js
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/notification/SendNotificationPage.vue
알림 삭제 로직 수정, 알림 상태 관리 구현
<br>
close #691 
<br>
> [eat#691] 알림 삭제 로직 수정, 알림 상태 관리 구현

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
- Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
- 자격증 조회 모달 수정
- 교육/자격증 날짜 포맷 함수 수정
close #695 
<br>
> [design/#695] 자격증 조회 모달 수정 및 교육/자격증 날짜 포맷 함수 수정

- Frontend/src/views/pages/admin/NoticeDetailPage.vue
> [design/#697] 공지사항 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/main/MainPage.vue
휴가일수 쿼터제, 월차에 맞게 차감 되도록 수정
<br>
close #701 
<br>
> [feat/#701] 휴가일수 쿼터제, 월차에 맞게 차감 되도록 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SalaryBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/schedule/SalarySchedule.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
급여 자동 생성 기능 구현
<br>
close #703 
<br>
> [feat/#703] 급여 자동 생성 기능 구현

- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/NoticeDetailPage.vue
> [design/#705] 공지사항 및 디테일 페이지 디자인 수정

- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/education/certificate-management/CertificationList.vue
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
<br>
글자 크기 수정
close #707 
<br>
> [design/#707] 교육 및 자격증 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
교육 관련 responseDTO 서비스단으로 옮김
<br>
close #709 
<br>
> [refactor#709] 교육 관련 responseDTO 서비스단으로 옮김

- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/AutoNotificationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
휴가취소 구현중
<br>
close #711 
<br>
> [feat/#711] 휴가취소 구현중

- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
responseDTO 서비스단으로 수정
<br>
close #713 
<br>
> [refactor#713] responseDTO 서비스단으로 수정

- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
> [design/#715] 교육 및 자격증 페이지 수정

- Backend/Heroes/src/main/java/com/hq/heroes/common/batch/SalaryBatch.java
- Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
날짜 형식 수정
비밀번호 변경 Dialog 디자인 수정
<br>
close #717 
<br>
> [design#717] 비밀번호 변경 Dialog 디자인 수정, 평가 날짜 형식 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
status 값 추가
<br>
close #{이슈넘버}
<br>
> refactor: status 값 추가

- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
- Frontend/src/views/pages/main/MainPage.vue
> [feat/#720] 휴가 관련기능

- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/salary/salary-statement.vue
total 급여 내역 생성
<br>
close #722 
<br>
> [design/#733] total 급여 내역 생성

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
- Frontend/src/views/pages/salary/salary-statement.vue
ACTIVE Employee List 추가 및 급여 명세서 디자인 수정
<br>
close #726 
<br>
> [refactor/#726] ACTIVE Employee List 추가 및 급여 명세서 디자인 수정

- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
education 상세 fetchGet 수정
<br>
close #728 
<br>
> [fix/#728] education 상세 fetchGet 수정

- Frontend/src/views/pages/admin/NoticeDetailPage.vue
NoticeDetailPage Button Style Change
<br>
close #730 
<br>
> [design/#730] NoticeDetailPage Button Style Change

- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
> [design/#732] 캘린더 필터 버튼, 사이드바 수정

- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
employee 퇴사 시 정보 수정 불가 및 자격증 페이지 디자인 수정
<br>
close #734 
<br>
> [refactor/#734] employee 퇴사 시 정보 수정 불가 및 자격증 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/AutoNotificationType.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
휴가 취소 기능 추가
<br>
close #736 
<br>
> [feat/#736] 휴가 취소 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
휴가 일수 차감 오류 수정
<br>
close #738 
<br>
> [fix/#738] 휴가 일수 차감 오류 수정

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
휴가 일수에서 주말은 제외하도록 설정
<br>
close #740 
<br>
> [feat/#740] 휴가 일수에서 주말은 제외하도록 설정

- Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
연장 근로 관련 기능 개발
<br>
close #742 
<br>
> [feat/#742] 연장 근로 관련 기능 개발

- Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
> [fix/#744] 교육 백엔드 코드 수정 및 에러 고침

- Frontend/src/layout/AttendanceBox.vue
> [design/#746] attendanceBox 수정

- Frontend/src/views/pages/admin/NoticeWritePage.vue
- Frontend/src/views/pages/retirement/retirement-funds.vue
공지사항 카테고리 수정 및 퇴직시 근무년수 기본값 설정
<br>
close #748 
<br>
> [refactor/#748/page] 공지사항 카테고리 수정 및 퇴직시 근무년수 기본값 설정

- Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
11/1 코드리뷰 버그 수정 : 비밀번호 변경 오류 수정, 평가일 기준으로 평가 결과 정렬
<br>
close #750 
<br>
> [fix#750] 11/1 코드리뷰 버그 수정 : 비밀번호 변경 오류 수정, 평가일 기준으로 평가 결과 정렬

- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
휴가 취소 신청, 승인, 반려 알림 자동 발송 구현
<br>
close #754 
<br>
> [feat#754] 휴가 취소 신청, 승인, 반려 알림 자동 발송 구현

- Frontend/src/views/pages/auth/LoginPage.vue
- Frontend/src/views/pages/auth/ResetPWPage.vue
로그인, 비밀번호 재발급 페이지 디자인 수정
<br>
close #756 
<br>
> [design#756] 로그인, 비밀번호 재발급 페이지 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/auth/service/AuthApiService.js
자격증 쪽 알림 자동 발송 DTO 문제 해결
<br>
close #758 
<br>
> [fix#758] 자격증 쪽 알림 자동 발송 DTO 문제 해결

- Frontend/src/layout/AttendanceBox.vue
출퇴근 버튼 클릭시 한번 더 물어보는 기능 추가
<br>
close #760 
<br>
> [feat/#760] 출퇴근 버튼 클릭시 한번 더 물어보는 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
취소 반려됨 추가해서 일수 차감 안되도록 수정
<br>
close #762 
<br>
> [feat/#762] 취소 반려됨 추가해서 일수 차감 안되도록 수정

- Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
연장 근로 신청 후 연장 신청 현황 페이지로 이동
<br>
close #764 
<br>
> [design/#764] 연장 근로 신청 후 연장 신청 현황 페이지로 이동

- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
vaction 반차 시 쿼터 단위로 신청 가능하게 수정
<br>
close #766 
<br>
> [fix/#766] vaction 반차 시 쿼터 단위로 신청 가능하게 수정

- Frontend/src/views/pages/admin/ManageNoticePage.vue
공지사항 수정 라우터 변경
<br>
close #768 
<br>
> [refactor/#768] 공지사항 수정 라우터 변경

- Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
날짜 형식 2024.11. 4 -> 2024-11-04 로 변경
<br>
close #774 
<br>
> [refactor/#774] 날짜 형식 2024.11. 4 -> 2024-11-04 로 변경

- Frontend/src/views/pages/salary/salary-statement.vue
salaryStatement design update
<br>
close #778 
<br>
> [design/#778] salaryStatement design update

- Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
- Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
- Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
승인 안된 대기중인 휴가일수의 합이 잔여 휴가일수 넘어갈 경우 제출 안되게 수정
<br>
close #780 
<br>
> [feat/#780] 승인 안된 대기중인 휴가일수의 합이 잔여 휴가일수 넘어갈 경우 제출 안되게 수정

- Frontend/src/views/pages/auth/SignUpPage.vue
<br>
회원가입시 부서에 속한 팀만 보이게 수정
close #782 
<br>
> [refactor/#782] 회원가입시 부서에 속한 팀만 보이게 수정

- Frontend/src/views/pages/salary/salary-statement.vue
급여 명세서 성과급 출력 조건 변경
<br>
close #788 
<br>
> [refactor/#788] 급여 명세서 성과급 출력 조건 변경

- Frontend/src/layout/AppMenu.vue
- Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
- Frontend/src/views/pages/HQattendance/overtime/approve-overtime.vue
- Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
- Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
- Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
- Frontend/src/views/pages/admin/ManageCertificatePage.vue
- Frontend/src/views/pages/admin/ManageEducationPage.vue
- Frontend/src/views/pages/admin/ManageNoticePage.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
- Frontend/src/views/pages/education/education-management/ApproveEducation.vue
- Frontend/src/views/pages/education/education-management/EducationApply.vue
- Frontend/src/views/pages/education/education-management/EducationHistory.vue
- Frontend/src/views/pages/employeeList/EmployeeListPage.vue
- Frontend/src/views/pages/evaluation/EvaluationListPage.vue
프론트 디자인 변경
<br>
close #790 
<br>
> [refactor/#790] 프론트 디자인 수정

- Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
- Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
- Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationsReqDTO.java
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
ToString 제거 및 JobId -> JobRoleId로 변경
<br>
close #793 
<br>
> [refactor/#793] ToString 제거 및 JobId -> JobRoleId로 변경

- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
- Frontend/src/views/pages/auth/SignUpPage.vue
- Frontend/src/views/pages/profile/ProfilePage.vue
front 기능 수정
<br>
close #795 
<br>
> [refactor/#795] front 기능 수정

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
개인 일정 삭제 기능 추가
<br>
close #797 
<br>
> [feat/#797] 개인 일정 삭제 기능 추가

- Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
- Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
- Frontend/src/views/pages/admin/EducationUpdatePage.vue
- Frontend/src/views/pages/admin/EducationWritePage.vue
- Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
- Frontend/src/views/pages/admin/NoticeUpdatePage.vue
- Frontend/src/views/pages/admin/NoticeWritePage.vue
- Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
- Frontend/src/views/pages/admin/service/adminNoticeService.js
- Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
- Frontend/src/views/pages/auth/AdminLoginPage.vue
- Frontend/src/views/pages/auth/service/fetchReissue.js
- Frontend/src/views/pages/education/education-management/EducationDetail.vue
- Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
- Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
- Frontend/src/views/pages/main/MainPage.vue
- Frontend/src/views/pages/main/service/noticeService.js
- Frontend/src/views/pages/main/service/notificationService.js
- Frontend/src/views/pages/retirement/service/retirementService.js
- Frontend/src/views/pages/salary/workService.js
캘린더 개인 일정 삭제 및 일정 변경 수정 기능 구현
<br>
close #799 
<br>
> [feat/#799] 캘린더 개인 일정 삭제 및 일정 변경 수정 기능 구현
